export const TEST_PRIVATE_ENV = {
	ORIGIN: 'https://app.example',
	CLIENT_IP_HEADER: 'X-Real-IP',
	TRUSTED_PROXY_ADDRESS: '127.0.0.1',
	WEBAUTHN_ORIGIN: 'https://example.com',
	WEBAUTHN_RP_ID: 'example.com',
	SMTP_HOST: 'localhost',
	SMTP_PORT: '587',
	SMTP_SECURE: 'false',
	SMTP_USER: '',
	SMTP_PASSWORD: '',
	SMTP_FROM: 'test@example.com',
	TURNSTILE_SITE_KEY: 'site-key',
	TURNSTILE_SECRET: 'secret-key',
	GITHUB_OAUTH_CLIENT_ID: undefined,
	GITHUB_OAUTH_CLIENT_SECRET: undefined,
	DISCORD_OAUTH_CLIENT_ID: undefined,
	DISCORD_OAUTH_CLIENT_SECRET: undefined,
	TWITCH_OAUTH_CLIENT_ID: undefined,
	TWITCH_OAUTH_CLIENT_SECRET: undefined
} as const;
