export enum GameSource {
	steam = 1,
	gog = 5,
	youtube = 10,
	microsoft = 11,
	apple = 13,
	twitch = 14,
	android = 15,
	amazon_asin = 20,
	amazon_luna = 22,
	amazon_adg = 23,
	epic_game_store = 26,
	oculus = 28,
	utomik = 29,
	itch_io = 30,
	xbox_marketplace = 31,
	kartridge = 32,
	playstation_store_us = 36,
	focus_entertainment = 37,
	xbox_game_pass_ultimate_cloud = 54,
	gamejolt = 55
}

export enum WebsiteCategory {
	official = 1,
	wikia = 2,
	wikipedia = 3,
	facebook = 4,
	twitter = 5,
	twitch = 6,
	instagram = 8,
	youtube = 9,
	iphone = 10,
	ipad = 11,
	android = 12,
	steam = 13,
	reddit = 14,
	itch = 15,
	epicgames = 16,
	gog = 17,
	discord = 18
}
